### ISSUE TITLE
Memory request?

### ISSUE THREAD

**Issue by XinWang19** [PayamDiba/SERGIO#7]
Hi, 
A really nice work! I have tried your software on our cluster with 64 GB available memory. But the program interrupted with this error:
########
Traceback (most recent call last):
  File "simulate.py", line 7, in <module>
    sim.build_graph("input_file_taregts.csv", "input_file_regs.csv")
  File "/lustre1/cxu_pkuhpc/wx/test/sergio/sergio.py", line 233, in build_graph
    self.find_levels_(self.graph_) # make sure that this modifies the graph
  File "/lustre1/cxu_pkuhpc/wx/test/sergio/sergio.py", line 281, in find_levels_
    self.level2verts_[currLayer] = []
MemoryError
pkurun: error: c13b02n03: task 0: Exited with exit code 1
########
The parameters I set were:
########
number_genes=210, number_bins=13, number_sc=50, noise_params=0.2,
    noise_type="dpd", decays=0, dynamics=False
########
Could you give me some suggestions about the memory requests under certain parameters?

**Comment by PayamDiba** [comment]
It's really weird that this setting of parameters results in memory error. I can imagine simulating 13 bins with ~1000 single-cell for each bin could results in memory error (that can be resolved easily for example by repeating simulation 10 times for 100 cell), but this setting should not give memory error. Can you try it on a PC with python 3 and let me know if you get error again? You don't need to compete the simulation on the PC, just check if simulations start, and please let me know.

**Comment by XinWang19** [comment]
Hi,
I tried on PC with python3. There was still something wrong.
###################
sim = sergio(number_genes=210, number_bins=13, number_sc=50, noise_params=0.2,noise_type="dpd", decays=0, dynamics=False)
sim.build_graph("input_file_taregts.csv", "input_file_regs.csv")
Traceback (most recent call last):
  File "C:\Users\dell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-aa66a50616a4>", line 1, in <module>
    sim.build_graph("input_file_taregts.csv", "input_file_regs.csv")
  File "D:\project201019\sergio.py", line 233, in build_graph
    self.find_levels_(self.graph_) # make sure that this modifies the graph
  File "D:\project201019\sergio.py", line 281, in find_levels_
    self.level2verts_[currLayer] = []
MemoryError

**Comment by PayamDiba** [comment]
Do you mind sharing with me the input files you are using?

**Comment by XinWang19** [comment]
https://disk.pku.edu.cn:443/link/370204CBD55E0DB504ACD12C77BBB80B
Thanks a lot.
