### ISSUE TITLE
Error in dynamic simulation

### ISSUE THREAD

**Issue by dosorio** [PayamDiba/SERGIO#8]
Hi @PayamDiba, thanks for writing SERGIO. I have been trying to do a dynamic simulation using your example, but I found a problem I cannot fix. Can you please help me to understand what the problem is?

Here is my code:
```
cat > iR.txt << EOF
0, 0.5, 1.5, 3
EOF

cat > iT.txt << EOF
1, 1, 0, 2.5, 2
2, 1, 1, -1.3, 2
EOF

cat > runSERGIO.py << EOF
import numpy as np
from sergio import sergio
np.random.seed(1)
sim = sergio(number_genes=3, number_bins = 3, number_sc = 100, 
             noise_params = 1, decays=2,
             noise_type='dpd', dynamics= True, bifurcation_matrix=[[0, 0.8, 0 ],[0, 0, 1.1], [0,0,0]])
sim.build_graph('iT.txt', 'iR.txt', shared_coop_state=1)
np.random.seed(1)
sim.simulate_dynamics()
np.random.seed(1)
expr = sim.getExpressions()
expr = np.concatenate(expr, axis = 1)
np.random.seed(1)
count_matrix = sim.convert_to_UMIcounts(expr)
np.savetxt('diffOutput.csv',count_matrix, delimiter=',')
EOF

python runSERGIO.py
```
This is the error:
```
Start simulating new cell type
Traceback (most recent call last):
  File "runSERGIO.py", line 9, in <module>
    sim.simulate_dynamics()
  File "/home/dcosorioh/SERGIO/sergio.py", line 839, in simulate_dynamics
    self.populate_with_parentCells_(bi)
  File "/home/dcosorioh/SERGIO/sergio.py", line 636, in populate_with_parentCells_
    g.append_Conc([self.binDict[parentBinID][g.ID].ss_U_ + deltaU[i]])
  File "/home/dcosorioh/SERGIO/gene.py", line 28, in append_Conc
    if currConc < 0:
TypeError: '<' not supported between instances of 'list' and 'int'
```

I really appreciate any help you can provide.

Daniel

**Comment by PayamDiba** [comment]
Hi Daniel, Thanks for the comment. This occurs due to a syntax difference between python 2 and python 3. We have modified it a while ago and I am assuming it should work fine now. Can you please clone the newest version and try the code again? Let me know if you still get the error.

**Comment by dosorio** [comment]
Hi @PayamDiba thank you very much! It works perfectly.

Best wishes,

Daniel
